version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/heidar/circleci-example
    steps:
      - checkout
      - run: go test -v ./...
